<script src="{{ asset('js/vendor/jquery-3.6.0.min.js') }}"></script>
        <script src="{{ asset('js/vendor/jquery-migrate-3.3.2.min.js') }}"></script>
		<!-- bootstrap js -->
        <script src="{{ asset('js/bootstrap.bundle.min.js') }}"></script>
		<!-- jquery.meanmenu js -->
        <script src="{{ asset('js/jquery.meanmenu.js') }}"></script>
		<!-- slick.min js -->
        <script src="{{ asset('js/slick.min.js') }}"></script>
		<!-- jquery.treeview js -->
        <script src="{{ asset('js/jquery.treeview.js') }}"></script>
		<!-- lightbox.min js -->
        <script src="{{ asset('js/lightbox.min.js') }}"></script>
		<!-- jquery-ui js -->
        <script src="{{ asset('js/jquery-ui.min.js') }}"></script>
		<!-- jquery.nivo.slider js -->
        <script src="{{ asset('lib/js/jquery.nivo.slider.js') }}"></script>
        <script src="{{ asset('lib/home.js') }}"></script>
		<!-- jquery.nicescroll.min js -->
        <script src="{{ asset('js/jquery.nicescroll.min.js') }}"></script>
		<!-- countdon.min js -->
        <script src="{{ asset('js/countdon.min.js') }}"></script>
		<!-- wow js -->
        <script src="{{ asset('js/wow.min.js') }}"></script>
		<!-- plugins js -->
        <script src="{{ asset('js/plugins.js') }}"></script>
		<!-- main js -->
        <script src="{{ asset('js/main.min.js') }}"></script>
